<?php

function hosting_platform_checkout_node_info() {
  $types["platform_checkout"] =  array(
    "type" => 'platform_checkout', "name" => 'Platform Checkout',
    "module" => 'platform_checkout',
    "has_title" => true, "title_label" => t('Platform Checkout'),
    "description" => hosting_node_help("platform_checkout"),
    "has_body" => 0, "body_label" => '', "min_word_count" => 0);
  return $types;
}

function hosting_platform_checkout_hosting_tasks() {
    $options = array();

    $options['site']['checkout'] = array(
        'title' => t('Checkout'),
        'description' => t('Checkout This Platform.'),
        'weight' => 1
    );
    return $options;
}

function hosting_platform_checkout_perm() {
    return array(
        'checkout a platform'
    );
}

function hosting_security_menu() {
  $items = array();
  $items['hosting/platformcheckout'] = array(
    'title' => 'Platform Checkout',
    'description' => 'Platform Checkout',
    'page callback' => 'hosting_platform_checkout',
    'access arguments' => array('checkout a platform'));

  return $items;
}

function hosting_platform_checkout_menu_access($node, $task) {
  if (user_access("checkout a platform")) {
    if ($node->type == 'platform') {
      // if the user can't edit this node, he can't create tasks on it
      if (!node_access('update', $node, $GLOBALS['user'])) {
        return FALSE;
      }
      // If the platform is in a deleted state, nothing else can be done with it
      if (hosting_task_outstanding($node->nid, 'delete') || ($node->platform_status ==  HOSTING_PLATFORM_DELETED)) {
        return FALSE;
      }
    
      $platform_tasks = array('verify', 'lock', 'delete', 'migrate');
      return (in_array($task, $platform_tasks));
    }

  }
  return FALSE;
}

